# Generated by Django 3.2 on 2021-04-25 00:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('second_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(default=datetime.date(2009, 4, 12))),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], default='MALE', max_length=10)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single')], default='SINGLE', max_length=10)),
                ('qualification', models.CharField(choices=[('NONE', 'None'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('ND/NCE', 'ND or NCE'), ('HND/HCE', 'HND or HCE'), ('BACHELOR', 'First Degree'), ('MASTERS', 'Masters')], default='NONE', max_length=20)),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('apply_date', models.DateField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=100)),
                ('status', models.BooleanField(choices=[(True, 'Employed'), (None, 'Pending'), (False, 'Not Employed')], default=True, null=True)),
            ],
        ),
    ]
