# Generated by Django 3.2 on 2021-04-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.BooleanField(choices=[(True, 'Employed'), (None, 'Pending'), (False, 'Rejected')], null=True),
        ),
    ]
