# Generated by Django 3.2.3 on 2021-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Employed'), (None, 'Pending'), (False, 'Rejected')], null=True),
        ),
    ]
