# Generated by Django 4.0.3 on 2022-05-02 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(default=datetime.date(2002, 5, 7)),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
