# Generated by Django 4.0.3 on 2022-05-03 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_alter_applicant_birth_date_alter_applicant_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(default=datetime.date(2002, 5, 8)),
        ),
    ]
