# Generated by Django 4.0.3 on 2022-05-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_alter_applicant_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
