# Generated by Django 4.0.3 on 2023-01-09 20:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0006_alter_applicant_birth_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicant',
            managers=[
                ('this_year', django.db.models.manager.Manager()),
            ],
        ),
    ]
