# Generated by Django 4.2.1 on 2023-06-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0007_alter_applicant_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Employed', 'Employed'), ('Terminated', 'Terminated'), ('Re-Engaged', 'Re-Engaged')], default='Applied', max_length=10),
        ),
    ]
