# Generated by Django 5.1.2 on 2025-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0008_applicant_state'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='applicant',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='applicant',
            name='state',
            field=models.CharField(default='Applied', max_length=10),
        ),
    ]
