# Generated by Django 6.0.2 on 2026-06-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0009_alter_applicant_managers_alter_applicant_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resignation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
