# Generated by Django 6.0.2 on 2026-06-06 00:18

import apply.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0010_add_resignation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apply.models._invite_expiry)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
