# Generated by Django 6.0.2 on 2026-06-06 01:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0011_applicationinvite'),
        ('staff', '0056_payroll_unique_staff_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='state',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Employed', 'Employed'), ('Rejected', 'Rejected'), ('Resigned', 'Resigned'), ('Re-Engaged', 'Re-Engaged')], default='Applied', max_length=10),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=4)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='apply.applicant')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to='staff.employee')),
            ],
        ),
    ]
