# Generated by Django 6.0.2 on 2026-06-06 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0012_alter_applicant_state_interview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='state',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Guarantor', 'Guarantor'), ('Employed', 'Employed'), ('Rejected', 'Rejected'), ('Resigned', 'Resigned'), ('Re-Engaged', 'Re-Engaged')], default='Applied', max_length=10),
        ),
        migrations.CreateModel(
            name='GuarantorDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='guarantor_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_doc', to='apply.applicant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
