# Generated by Django 6.0.2 on 2026-06-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0013_alter_applicant_state_guarantordocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='state',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Guarantor', 'Guarantor'), ('Employed', 'Employed'), ('Rejected', 'Rejected'), ('Resigned', 'Resigned'), ('Sacked', 'Sacked'), ('Re-Engaged', 'Re-Engaged')], default='Applied', max_length=10),
        ),
    ]
