# Generated by Django 6.0.2 on 2026-06-10 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0014_alter_applicant_state_add_sacked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantordocument',
            name='reupload_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guarantordocument',
            name='reupload_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor_reupload_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guarantordocument',
            name='reupload_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantordocument',
            name='reupload_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guarantordocument',
            name='reupload_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guarantordocument',
            name='reupload_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor_reupload_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
