# Generated by Django 3.2.4 on 2021-07-04 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=15, unique=True)),
                ('order_number', models.CharField(max_length=15)),
                ('created_date', models.DateField(default=datetime.datetime.today)),
                ('stage', models.CharField(default='CREATED', max_length=10)),
                ('transporter', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('confirm', models.BooleanField(default=False)),
                ('products', models.JSONField()),
                ('source', models.CharField(choices=[('GN', 'Guinness'), ('NB', 'Nigerian Breweries'), ('IB', "Int'l Breweries"), ('SELLWELL', 'Sellwell'), ('MD', 'Monument Distillers'), ('FAREAST', 'FarEast'), ('Hayat', 'Hayat')], max_length=50)),
                ('ship_to', models.CharField(choices=[('TRADE FAIR', 'Trade fair'), ('ISLAND', 'Island'), ('BADAGRY', 'Badagry'), ('STARDOM', 'Stardom')], max_length=20)),
                ('delivered_to', models.CharField(max_length=20)),
                ('credit', models.BooleanField(default=False)),
                ('remark', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
