# Generated by Django 4.0a1 on 2021-11-25 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0031_alter_requestpermission_date_and_more'),
        ('users', '0003_remove_profile_bio_remove_profile_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
    ]
