# Generated by Django 4.0a1 on 2021-12-16 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_alter_creditnote_period_alter_debitnote_period_and_more'),
        ('users', '0004_alter_profile_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
    ]
