# Generated by Django 4.0.3 on 2022-06-05 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stock_report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
