# Generated by Django 3.2 on 2021-04-25 00:46

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('NB', 'NBPlc'), ('GN', 'GNPlc'), ('IB', "Int'l Plc"), ('FE', 'FarEast'), ('SW', 'SellWell'), ('MD', 'Monument'), ('FN', 'Fouani'), ('MSC', 'Miscellaneous'), ('Hayat', 'Hayat')], max_length=50)),
                ('category', models.CharField(choices=[('Malt', 'Malt'), ('Lager', 'Lager'), ('Stout', 'Stout'), ('RTD', 'RTD'), ('ED', 'Energy Drink'), ('Bitters', 'Bitters'), ('Soft', 'Soft Drink'), ('H2O', 'Water'), ('NA Wine', 'Non Alcoholic Wine'), ('Wine', 'Alcoholic Wine')], max_length=50)),
                ('unit_price_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('unit_price', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8)),
                ('pack_type', models.CharField(choices=[('Pieces', 'Pieces'), ('Pack', 'Pack'), ('Pallet', 'Pallet')], default='Pack', max_length=20)),
                ('quantity_per_pack', models.IntegerField(default=24)),
                ('unit_type', models.CharField(default='Can', max_length=20)),
                ('product_state', models.CharField(choices=[('Liquid', 'Liquid'), ('Solid', 'Solid'), ('Gas', 'Gas')], default='Liquid', max_length=20)),
                ('size_value', models.FloatField(blank=True, default=33, null=True)),
                ('size_value_unit', models.CharField(blank=True, choices=[('ml', 'Millilitres'), ('cl', 'Centilitres'), ('l', 'Litres')], default='cl', max_length=20, null=True)),
                ('alcohol_content', models.FloatField(default=0.0)),
                ('vat', models.FloatField(choices=[(7.5, 'Vatted'), (0.0, 'Exempted')], default=7.5)),
                ('image', models.ImageField(default='default.jpg', upload_to='product_pics')),
                ('cost_price_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('cost_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='NGN', max_digits=8)),
                ('parameter', models.CharField(max_length=20)),
                ('active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True)),
            ],
        ),
    ]
