# Generated by Django 3.2 on 2021-05-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parameter',
            field=models.CharField(help_text='<span class="text-danger">types but of same price e.g. maltina classic, maltina pineaple</span>', max_length=20),
        ),
    ]
