# Generated by Django 3.2.4 on 2021-06-20 10:51

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_product_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
