# Generated by Django 3.2.4 on 2021-07-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210620_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_type',
            field=models.CharField(choices=[('PP', 'Per Pack'), ('PERCENT', 'Percent'), ('VALUE', 'Absolute Value'), ('RATIO', 'Qty Ratio')], default='PP', max_length=20),
        ),
    ]
