# Generated by Django 3.2.4 on 2021-07-10 16:33

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210704_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='NGN', max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Can', 'Can'), ('Pet', 'Pet'), ('Bottle', 'Bottle'), ('Tetra', 'Tetra Pak'), ('Crate', 'Crate')], default='Can', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.FloatField(choices=[(7.5, 'Vatable'), (0.0, 'Exempted')], default=7.5),
        ),
    ]
