# Generated by Django 3.2.4 on 2021-07-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20210710_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('NB', 'NBPlc'), ('GN', 'GNPlc'), ('IB', "Int'l Plc"), ('FE', 'FarEast'), ('SW', 'SellWell'), ('MD', 'Monument'), ('FN', 'Fouani'), ('HY', 'Hayat'), ('MSC', 'Miscellaneous')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Can', 'Can'), ('Pet', 'Pet'), ('Bottle', 'Bottle'), ('Tetra', 'Tetra Pak'), ('Crate', 'Crate'), ('Sachet', 'Sachet')], default='Can', max_length=20),
        ),
    ]
