# Generated by Django 3.2.4 on 2021-07-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20210714_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Malt', 'Malt'), ('Lager', 'Lager'), ('Stout', 'Stout'), ('RTD', 'RTD'), ('ED', 'Energy Drink'), ('Bitters', 'Bitters'), ('Soft', 'Soft Drink'), ('Others', 'Others'), ('NA Wine', 'Non Alcoholic Wine'), ('Wine', 'Alcoholic Wine')], max_length=50),
        ),
    ]
