# Generated by Django 4.0a1 on 2021-11-11 08:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
        ('stock', '0008_product_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(1, 'NGN'), message="Cost price can't must be 0.00")]),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('NB', 'NBPlc'), ('GN', 'GNPlc'), ('IB', "Int'l Plc"), ('FE', 'FarEast'), ('SW', 'SellWell'), ('MD', 'Monument'), ('GG', 'Golden Guinea'), ('BD', 'BigDist'), ('MSC', 'Miscellaneous')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('landing_cost_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('landing_cost', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='NGN', max_digits=8)),
                ('selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('selling_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='NGN', max_digits=8)),
                ('depletion', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('tag', models.BooleanField(default=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.salescenter')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
    ]
