# Generated by Django 4.0.3 on 2022-03-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_productextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_stock_valued',
            field=models.BooleanField(default=False),
        ),
    ]
