# Generated by Django 4.0.3 on 2022-03-14 07:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_product_is_stock_valued'),
    ]

    operations = [
        migrations.AddField(
            model_name='productextension',
            name='cost_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1000'), default_currency='NGN', max_digits=8, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(1, 'NGN'), message="Cost price can't be NGN0.00")]),
        ),
        migrations.AddField(
            model_name='productextension',
            name='cost_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='productextension',
            name='selling_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1000'), default_currency='NGN', max_digits=8, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(1, 'NGN'), message="Selling price can't be NGN0.00")]),
        ),
        migrations.AddField(
            model_name='productextension',
            name='selling_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(1, 'NGN'), message="Cost price can't be NGN0.00")]),
        ),
        migrations.AlterField(
            model_name='productextension',
            name='stock_value',
            field=models.IntegerField(default=0),
        ),
    ]
