# Generated by Django 4.0.3 on 2022-03-14 08:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_productextension_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productextension',
            name='sales_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=12, validators=[django.core.validators.MinValueValidator(djmoney.money.Money(0, 'NGN'), message="Sales amount can't be negative")]),
        ),
        migrations.AddField(
            model_name='productextension',
            name='sales_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='productextension',
            name='sell_out',
            field=models.IntegerField(default=0),
        ),
    ]
