# Generated by Django 4.0.3 on 2022-04-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_productextension_sales_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Malt', 'Malt'), ('Lager', 'Lager'), ('Stout', 'Stout'), ('RTD', 'RTD'), ('Energy', 'Energy'), ('Bitters', 'Bitters'), ('Soft', 'Soft'), ('Wine', 'Wine'), ('NA Wine', 'NA Wine'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_type',
            field=models.CharField(choices=[('Can', 'Can'), ('Pet', 'Pet'), ('Bottle', 'Bottle'), ('Tetra Pak', 'Tetra Pak'), ('Crate', 'Crate'), ('Sachet', 'Sachet')], default='Pack', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='parameter',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Ultra', 'Ultra'), ('Vanilla', 'Vanilla'), ('Apple', 'Apple'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('Standard', 'Standard'), ('Normal', 'Normal')], default='Normal', help_text='<span class="text-danger">types but of same price e.g. maltina classic, maltina pineaple</span>', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_value_unit',
            field=models.CharField(blank=True, choices=[('ML', 'ML'), ('CL', 'CL'), ('L', 'L')], default='cl', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('NB', 'NB'), ('GN', 'GN'), ('IB', 'IB'), ('MSS', 'MSS'), ('IPS', 'IPS'), ('Monument', 'Monument'), ('Crates', 'Crates'), ('Empties', 'Empties'), ('Others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('Pieces', 'Pieces'), ('Pack', 'Pack'), ('Pallet', 'Pallet')], default='Can', max_length=20),
        ),
    ]
