# Generated by Django 4.0.3 on 2022-04-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_product_category_alter_product_pack_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parameter',
            field=models.CharField(default='Standard', help_text='<span class="text-danger">products of the same name but different shape or flavour e.g. maltina: classic, pineaple, vanilla</span>', max_length=20, verbose_name='Flavour, Shape or Size'),
        ),
    ]
