# Generated by Django 4.0.3 on 2022-04-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_product_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_value_unit',
            field=models.CharField(blank=True, choices=[('ML', 'ML'), ('CL', 'CL'), ('L', 'L')], default='CL', max_length=20, null=True),
        ),
    ]
