# Generated by Django 4.0.3 on 2022-05-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_alter_product_size_value_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watchlist',
            field=models.BooleanField(default=False, verbose_name='watchlist'),
        ),
    ]
