# Generated by Django 4.0.3 on 2022-05-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_product_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productextension',
            name='status',
        ),
        migrations.AddField(
            model_name='productextension',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
