# Generated by Django 4.0.3 on 2022-07-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_remove_productextension_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productextension',
            name='stock_value',
            field=models.IntegerField(default=0, verbose_name='quantity'),
        ),
    ]
