# Generated by Django 4.0.3 on 2022-11-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_alter_productextension_stock_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pack_type',
            field=models.CharField(default='Pack', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_state',
            field=models.CharField(default='Liquid', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_value_unit',
            field=models.CharField(blank=True, default='CL', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_type',
            field=models.CharField(default='Can', max_length=20),
        ),
    ]
