# Generated by Django 4.0.3 on 2023-03-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_alter_product_category_alter_product_pack_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='velocity',
            field=models.IntegerField(default=-1),
        ),
    ]
