# Generated by Django 6.0.2 on 2026-06-11 02:36

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_product_velocity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_stock_level',
            field=models.IntegerField(default=0, help_text='Maximum stock to hold (in units). 0 = not set', verbose_name='Maximum Stock Level'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock_level',
            field=models.IntegerField(default=0, help_text='Minimum stock to hold (in units). 0 = not set', verbose_name='Minimum Stock Level'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(default=0, help_text='Trigger reorder when stock falls to/below this. 0 = not set', verbose_name='Reorder Point'),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_qty',
            field=models.IntegerField(default=0, help_text='Suggested quantity to reorder. 0 = not set', verbose_name='Reorder Quantity'),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('COST', 'Cost'), ('SELLING', 'Selling')], max_length=10)),
                ('old_price_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('old_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('new_price_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('new_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stock.product')),
            ],
            options={
                'verbose_name_plural': 'Price histories',
                'ordering': ['-date'],
            },
        ),
    ]
