# Generated by Django 6.0.2 on 2026-06-11 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('RECEIPT', 'Receipt'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('TRANSFER', 'Transfer'), ('ADJUSTMENT', 'Adjustment'), ('WRITE_OFF', 'Write-off')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Use a negative number to reduce stock')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stock.product')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
