# Generated by Django 6.0.2 on 2026-06-05 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(default='Lagos, Nigeria', max_length=100)),
                ('description', models.TextField(help_text='Roles and responsibilities')),
                ('requirements', models.TextField(help_text='Qualifications and experience required')),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('contact_email', models.EmailField(default='careers@ozonefl.com', max_length=254)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-posted_date'],
            },
        ),
    ]
