# Generated by Django 6.0.2 on 2026-06-05 23:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='contact_email',
            field=models.EmailField(default='contact@ozonefl.com', max_length=254),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('education', models.TextField(blank=True, help_text='Highest qualification and institution')),
                ('experience', models.TextField(blank=True, help_text='Relevant work experience')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Form Submitted'), ('interview', 'Interview Granted'), ('accepted', 'Accepted – Awaiting Guarantor'), ('employed', 'Employed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('hr_notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('employer', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(blank=True, help_text='Relationship to applicant', max_length=100)),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID Card'), ('passport', 'International Passport'), ('drivers', "Driver's Licence"), ('voters', "Voter's Card")], max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=60)),
                ('agreed', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='jobs.jobapplication')),
            ],
            options={
                'verbose_name': 'Guarantor',
                'verbose_name_plural': 'Guarantors',
            },
        ),
    ]
