# Generated by Django 6.0.2 on 2026-06-05 23:52

import jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobposting_contact_email_jobapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantor',
            name='link_expires_at',
            field=models.DateTimeField(default=jobs.models._default_link_expiry),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='link_expires_at',
            field=models.DateTimeField(default=jobs.models._default_link_expiry),
        ),
    ]
