# Generated by Django 4.0a1 on 2021-10-24 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0028_employeebalance_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
