# Generated by Django 6.0.2 on 2026-06-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_jsondataset_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('list', 'List')], default='text', max_length=10)),
                ('text_value', models.TextField(blank=True, default='')),
                ('list_value', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
    ]
