# Generated by Django 6.0.2 on 2026-07-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=150)),
                ('rc_number', models.CharField(blank=True, max_length=30, verbose_name='RC Number')),
                ('tin', models.CharField(blank=True, max_length=30, verbose_name='TIN')),
                ('date_incorporated', models.DateField(blank=True, null=True)),
                ('registered_address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company')),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('head_office_address', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True, verbose_name='X (Twitter)')),
                ('instagram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
