# Generated by Django 4.0.3 on 2022-11-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=120)),
                ('cluster', models.CharField(choices=[('TRF', 'Trade Fair'), ('FES', 'Festac'), ('OMO', 'Omonile'), ('OKO', 'Okoko'), ('BAD', 'Badagry'), ('SAT', 'Satellite'), ('BAR', 'Barracks'), ('LIS', 'Lagos Island'), ('NC', 'No Cluster')], default='TRF', max_length=13)),
                ('region', models.CharField(choices=[('LOS', 'Lagos'), ('DSP', 'Diaspora'), ('OLS', 'Outside Lagos')], default='LOS', max_length=13)),
                ('mobile', models.CharField(max_length=14)),
                ('second_mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, help_text="<span class='text-danger'>not compulsory</span>", max_length=254, null=True)),
                ('classification', models.CharField(choices=[('RTN', 'Returnable'), ('OWP', '1-Way Pack'), ('WIN', 'Wine'), ('ROW', 'Returnable+1-Way'), ('OWW', '1-Way+Wine'), ('ALL', 'All'), ('RTW', 'Returnable+Wine')], default='OWP', max_length=20)),
                ('contact_person', models.CharField(blank=True, help_text='firstname, mobile number', max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
