# Generated by Django 3.2 on 2021-04-25 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('cluster', models.CharField(choices=[('TRADE FAIR', 'Trade Fair'), ('FESTAC', 'Festac'), ('OKOKO', 'Okoko'), ('BADAGRY', 'Badagry'), ('SATELLITE', 'Satellite'), ('DIASPORA', 'Diaspora')], max_length=30)),
                ('category', models.CharField(choices=[('BRASS', 'Brass'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, help_text="<span class='text-danger'>not compulsory</span>", max_length=254, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.CharField(choices=[('LAGOS', 'Lagos')], default='LAGOS', max_length=30)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
