# Generated by Django 4.0.3 on 2022-12-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='profile',
            name='second_mobile',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
