# Generated by Django 3.2.4 on 2021-09-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='creator',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
