# Generated by Django 4.0.3 on 2022-11-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile_alter_customerprofile_cluster_and_more'),
    ]

    # operations = [
    #     migrations.DeleteModel(
    #         name='Profile',
    #     ),
    # ]
