# Generated by Django 4.0.3 on 2022-12-09 13:59

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_stock_report_date'),
        ('customer', '0002_alter_profile_mobile_alter_profile_second_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_person',
            field=models.CharField(blank=True, help_text='format: firstname-mobile', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('credit_limit', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('current_credit_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('current_credit', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField()),
                ('isPermanent', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile')),
                ('customerID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.profile')),
            ],
        ),
    ]
