# Generated by Django 3.2.4 on 2021-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210905_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='type',
            field=models.CharField(default='A-Drink', max_length=20),
        ),
    ]
