# Generated by Django 3.2.4 on 2021-09-05 11:17

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customerprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='sales',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=12),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='sales_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
