# Generated by Django 4.0.3 on 2022-11-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
