# Generated by Django 4.0.3 on 2022-12-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_profile_contact_person_customercredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_person',
            field=models.CharField(blank=True, help_text='format: firstname//mobile', max_length=50, null=True),
        ),
    ]
