# Generated by Django 3.2.4 on 2021-09-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210905_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='freq',
            field=models.IntegerField(default=0),
        ),
    ]
