# Generated by Django 4.0.3 on 2022-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_profile_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercredit',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'Active'), (None, 'Blacklist'), (False, 'Disable')], default=True, null=True),
        ),
    ]
