# Generated by Django 4.2.1 on 2023-06-05 23:25

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customercredit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercredit',
            name='credit_limit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='customercredit',
            name='current_credit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
