# Generated by Django 3.2.4 on 2021-09-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customerprofile_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='type',
            field=models.CharField(default='NA-Can', max_length=50),
        ),
    ]
