# Generated by Django 4.0a1 on 2021-12-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customerprofile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='section',
            field=models.CharField(choices=[('C & B', 'Crate & Bottle'), ('W & W', 'Wine & Whisky'), ('C & P', 'Cans & Pet')], default='C & P', max_length=10),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='type',
            field=models.CharField(choices=[('NA', 'Non-Alcoholic'), ('A', 'Alcoholic'), ('U', 'Unknown')], default='NA', max_length=10),
        ),
    ]
