# Generated by Django 4.0a1 on 2022-02-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customerprofile_section_alter_customerprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='section',
            field=models.CharField(default='C & P', max_length=30),
        ),
    ]
