# Generated by Django 4.0.3 on 2022-11-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_customerprofile_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='sales_currency',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='section',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='type',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='classification',
            field=models.CharField(choices=[('RTN', 'Returnable'), ('OWP', '1-Way Pack'), ('WIN', 'Wine'), ('ROP', 'Returnable + 1-Way Pack'), ('OWW', '1-Way Pack + Wine'), ('ALL', 'All'), ('RTW', 'Returnable + Wine')], default='OWP', max_length=3),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='contact_person',
            field=models.CharField(blank=True, help_text='firstname, mobile number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='second_mobile',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cluster',
            field=models.CharField(choices=[('TRF', 'Trade Fair'), ('FST', 'Festac'), ('OKO', 'Okoko'), ('BDG', 'Badagry'), ('STL', 'Satellite'), ('BRK', 'Barracks'), ('LIS', 'Lagos Island'), ('NC', 'No Cluster')], default='TRF', max_length=3),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='mobile',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='region',
            field=models.CharField(choices=[('LOS', 'Lagos'), ('DSP', 'Diaspora'), ('OLS', 'Outside Lagos')], default='LOS', max_length=3),
        ),
    ]
