# Generated by Django 4.0.3 on 2022-11-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_customerprofile_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='cluster',
            field=models.CharField(choices=[('TRF', 'Trade Fair'), ('FST', 'Festac'), ('OMO', 'Omonile'), ('OKO', 'Okoko'), ('BDG', 'Badagry'), ('SAT', 'Satellite'), ('BAR', 'Barracks'), ('LIS', 'Lagos Island'), ('NC', 'No Cluster')], default='TRF', max_length=3),
        ),
    ]
