# Generated by Django 4.0.3 on 2022-11-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_customerprofile_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='classification',
            field=models.CharField(choices=[('RTN', 'Returnable'), ('OWP', '1-Way Pack'), ('WIN', 'Wine'), ('ROW', 'Returnable+1-Way'), ('OWW', '1-Way+Wine'), ('ALL', 'All'), ('RTW', 'Returnable+Wine')], default='OWP', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='cluster',
            field=models.CharField(choices=[('TRF', 'Trade Fair'), ('FES', 'Festac'), ('OMO', 'Omonile'), ('OKO', 'Okoko'), ('BAD', 'Badagry'), ('SAT', 'Satellite'), ('BAR', 'Barracks'), ('LIS', 'Lagos Island'), ('NC', 'No Cluster')], default='TRF', max_length=13),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='region',
            field=models.CharField(choices=[('LOS', 'Lagos'), ('DSP', 'Diaspora'), ('OLS', 'Outside Lagos')], default='LOS', max_length=13),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='second_mobile',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
