# Generated by Django 4.0.3 on 2022-04-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dispatch',
            field=models.BooleanField(default=False),
        ),
    ]
