# Generated by Django 3.2 on 2021-04-25 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_date', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.CharField(max_length=50)),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_date', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.CharField(max_length=50)),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='staff_pics')),
                ('date_employed', models.DateField(default=django.utils.timezone.now, help_text='<em style=color:red;>YYYY-MM-DD</em>')),
                ('official_email', models.EmailField(blank=True, help_text='<em style=color:red;>firstname.lastname@ozonefl.com</em>', max_length=50, null=True)),
                ('official_mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('is_management', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('position', models.CharField(blank=True, choices=[('Cashier', 'Cashier'), ('Store-Keeper', 'Store-Keeper'), ('Stock-Keeper', 'Stock-Keeper'), ('Accounts-Clerk', 'Accounts-Clerk'), ('Sales-Clerk', 'Sales-Clerk'), ('Accountant', 'Accountant'), ('HRM', 'HRM'), ('SCM', 'SCM'), ('GSM', 'GSM'), ('MD', 'Managing Director'), ('Analyst', 'Analyst'), ('Sales Rep', 'Sales Rep'), ('Marketing Manager', 'Marketing Manager')], max_length=30, null=True)),
                ('department', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Admin', 'Admin'), ('Accounts', 'Accounts'), ('HR', 'HR')], max_length=30, null=True)),
                ('branch', models.CharField(blank=True, choices=[('HQ', 'HQ'), ('FG', 'FG'), ('Genesis', 'Genesis')], max_length=30, null=True)),
                ('banker', models.CharField(choices=[('Access', 'Access'), ('Ecobank', 'Ecobank'), ('FCMB', 'FCMB'), ('Fidelity', 'Fidelity'), ('First Bank', 'First Bank'), ('GTB', 'GTB'), ('Heritage', 'Heritage'), ('Polaris', 'Polaris'), ('Stanbic', 'Stanbic'), ('Sterling', 'Sterling'), ('UBA', 'UBA'), ('Union Bank', 'Union Bank'), ('Zenith', 'Zenith')], default='UBA', max_length=20)),
                ('account_number', models.CharField(max_length=10)),
                ('basic_salary_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('basic_salary', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8, validators=[djmoney.models.validators.MinMoneyValidator(15000), djmoney.models.validators.MaxMoneyValidator(200000)])),
                ('allowance_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('allowance', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8)),
                ('tax_amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('tax_amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=6)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (None, 'Passive'), (False, 'Terminated')], default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='StaffStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('note', models.CharField(max_length=100)),
                ('opening_balance_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('opening_balance', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8)),
                ('closing_balance_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3)),
                ('closing_balance', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.creditnote')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.debitnote')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
        migrations.AddField(
            model_name='debitnote',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee'),
        ),
    ]
