# Generated by Django 3.2 on 2021-05-04 04:54

from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffstatement',
            name='closing_balance',
        ),
        migrations.RemoveField(
            model_name='staffstatement',
            name='closing_balance_currency',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='remark',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='allowance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(30000)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=6, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(5000)]),
        ),
    ]
