# Generated by Django 3.2 on 2021-05-04 06:14

from django.db import migrations, models
import django.db.models.deletion
import djmoney.money


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210504_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffstatement',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffstatement',
            name='credit_note',
            field=models.ForeignKey(default=djmoney.money.Money(0, 'NGN'), on_delete=django.db.models.deletion.CASCADE, to='staff.creditnote'),
        ),
        migrations.AlterField(
            model_name='staffstatement',
            name='debit_note',
            field=models.ForeignKey(default=djmoney.money.Money(0, 'NGN'), on_delete=django.db.models.deletion.CASCADE, to='staff.debitnote'),
        ),
    ]
