# Generated by Django 3.2 on 2021-05-04 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20210504_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffstatement',
            name='credit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.creditnote'),
        ),
        migrations.AlterField(
            model_name='staffstatement',
            name='debit_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.debitnote'),
        ),
    ]
