# Generated by Django 3.2 on 2021-05-09 23:07

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_payroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
