# Generated by Django 3.2 on 2021-05-12 09:07

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20210510_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='debit',
        ),
        migrations.AddField(
            model_name='payroll',
            name='credit_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='credit_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='payroll',
            name='debit_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='debit_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='payroll',
            name='deduction',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='deduction_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_pay',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_pay_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='payroll',
            name='outstanding',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='outstanding_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='allowance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(300000)]),
        ),
    ]
