# Generated by Django 3.2 on 2021-05-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20210512_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='balance_currency',
        ),
    ]
