# Generated by Django 3.2.3 on 2021-06-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20210512_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2021-06', max_length=7),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2021-06', max_length=7),
        ),
    ]
