# Generated by Django 3.2.4 on 2021-06-20 10:51

from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20210604_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='allowance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8, validators=[djmoney.models.validators.MinMoneyValidator(1000), djmoney.models.validators.MaxMoneyValidator(200000)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='basic_salary_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Terminated')], default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='staffstatement',
            name='opening_balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
