# Generated by Django 3.2.4 on 2021-06-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20210620_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='banker',
            field=models.CharField(choices=[('Access', 'Access'), ('Ecobank', 'Ecobank'), ('FCMB', 'FCMB'), ('Fidelity', 'Fidelity'), ('First Bank', 'First Bank'), ('GTB', 'GTB'), ('Heritage', 'Heritage'), ('Polaris', 'Polaris'), ('Stanbic', 'Stanbic'), ('Sterling', 'Sterling'), ('UBA', 'UBA'), ('Union Bank', 'Union Bank'), ('Unity', 'Unity'), ('Wema', 'Wema'), ('Zenith', 'Zenith')], default='UBA', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(blank=True, choices=[('HQ', 'HQ'), ('FG', 'FG'), ('Genesis', 'Genesis'), ('Stardom', 'Stardom'), ('Vino', 'Vino'), ('Island', 'Island'), ('Badagry', 'Badagry')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[('Cashier', 'Cashier'), ('Store-Keeper', 'Store-Keeper'), ('Stock-Keeper', 'Stock-Keeper'), ('Accounts-Clerk', 'Accounts-Clerk'), ('Sales-Clerk', 'Sales-Clerk'), ('Accountant', 'Accountant'), ('HRM', 'HRM'), ('SCM', 'SCM'), ('GSM', 'GSM'), ('MD', 'Managing Director'), ('Analyst', 'Analyst'), ('Sales Rep', 'Sales Rep'), ('Marketing Manager', 'Marketing Manager'), ('Driver', 'Driver')], max_length=30, null=True),
        ),
    ]
