# Generated by Django 3.2.4 on 2021-06-27 23:17

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20210628_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='salary',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='salary_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
