# Generated by Django 3.2.4 on 2021-07-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20210628_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2021-07', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2021-07', max_length=7),
        ),
    ]
