# Generated by Django 3.2.4 on 2021-07-17 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20210704_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_type', models.CharField(choices=[('Resign', 'Resign'), ('Sack', 'Sack')], default='Resign', max_length=6)),
                ('remark', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Reassign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassign_type', models.CharField(choices=[('Temporal', 'Temporal'), ('Permanent', 'Permanent')], default='Temporal', max_length=10)),
                ('from_position', models.CharField(blank=True, choices=[('Cashier', 'Cashier'), ('Store-Keeper', 'Store-Keeper'), ('Stock-Keeper', 'Stock-Keeper'), ('Accounts-Clerk', 'Accounts-Clerk'), ('Sales-Clerk', 'Sales-Clerk'), ('Accountant', 'Accountant'), ('HRM', 'HRM'), ('SCM', 'SCM'), ('GSM', 'GSM'), ('MD', 'Managing Director'), ('Analyst', 'Analyst'), ('Sales Rep', 'Sales Rep'), ('Marketing Manager', 'Marketing Manager'), ('Driver', 'Driver')], max_length=30, null=True)),
                ('to_position', models.CharField(blank=True, choices=[('Cashier', 'Cashier'), ('Store-Keeper', 'Store-Keeper'), ('Stock-Keeper', 'Stock-Keeper'), ('Accounts-Clerk', 'Accounts-Clerk'), ('Sales-Clerk', 'Sales-Clerk'), ('Accountant', 'Accountant'), ('HRM', 'HRM'), ('SCM', 'SCM'), ('GSM', 'GSM'), ('MD', 'Managing Director'), ('Analyst', 'Analyst'), ('Sales Rep', 'Sales Rep'), ('Marketing Manager', 'Marketing Manager'), ('Driver', 'Driver')], max_length=30, null=True)),
                ('from_branch', models.CharField(blank=True, choices=[('HQ', 'HQ'), ('FG', 'FG'), ('Genesis', 'Genesis'), ('Stardom', 'Stardom'), ('Vino', 'Vino'), ('Island', 'Island'), ('Badagry', 'Badagry')], max_length=30, null=True)),
                ('to_branch', models.CharField(blank=True, choices=[('HQ', 'HQ'), ('FG', 'FG'), ('Genesis', 'Genesis'), ('Stardom', 'Stardom'), ('Vino', 'Vino'), ('Island', 'Island'), ('Badagry', 'Badagry')], max_length=30, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('remark', models.CharField(max_length=100)),
                ('duration', models.SmallIntegerField(default=360)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
