# Generated by Django 3.2.4 on 2021-07-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_reassign_terminate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reassign',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='reassign',
            name='from_branch',
        ),
        migrations.RemoveField(
            model_name='reassign',
            name='from_position',
        ),
    ]
