# Generated by Django 3.2.4 on 2021-07-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20210717_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassign',
            name='from_branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reassign',
            name='from_position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
