# Generated by Django 3.2.4 on 2021-07-20 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_auto_20210717_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('resumption_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=100)),
                ('penalty_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('penalty', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=7)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('ending_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=100)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
