# Generated by Django 3.2.4 on 2021-07-28 01:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_permit_suspend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, choices=[['Cashier', 'Cashier'], ['Store-Keeper', 'Store-Keeper'], ['Stock-Keeper', 'Stock-Keeper'], ['Accounts-Clerk', 'Accounts-Clerk'], ['Sales-Clerk', 'Sales-Clerk'], ['Accountant', 'Accountant'], ['HRM', 'HRM'], ['SCM', 'SCM'], ['GSM', 'GSM'], ['MD', 'Managing Director'], ['Analyst', 'Analyst'], ['Sales Rep', 'Sales Rep'], ['Marketing Manager', 'Marketing Manager'], ['Driver', 'Driver']], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reassign',
            name='to_position',
            field=models.CharField(blank=True, choices=[['Cashier', 'Cashier'], ['Store-Keeper', 'Store-Keeper'], ['Stock-Keeper', 'Stock-Keeper'], ['Accounts-Clerk', 'Accounts-Clerk'], ['Sales-Clerk', 'Sales-Clerk'], ['Accountant', 'Accountant'], ['HRM', 'HRM'], ['SCM', 'SCM'], ['GSM', 'GSM'], ['MD', 'Managing Director'], ['Analyst', 'Analyst'], ['Sales Rep', 'Sales Rep'], ['Marketing Manager', 'Marketing Manager'], ['Driver', 'Driver']], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SalaryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('remark', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
