# Generated by Django 3.2.4 on 2021-07-28 01:30

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_auto_20210728_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarychange',
            name='previous_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='salarychange',
            name='previous_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3),
        ),
    ]
