# Generated by Django 3.2.4 on 2021-08-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_auto_20210728_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2021-08', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2021-08', max_length=7),
        ),
        migrations.AlterField(
            model_name='reassign',
            name='reassign_type',
            field=models.CharField(choices=[('Temporal', 'Temporal'), ('Acting', 'Acting'), ('Permanent', 'Permanent')], default='Temporal', max_length=10),
        ),
    ]
