# Generated by Django 3.2.4 on 2021-08-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_auto_20210809_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassign',
            name='duration',
            field=models.SmallIntegerField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='reassign',
            name='reassign_type',
            field=models.CharField(choices=[('T', 'Temporal'), ('A', 'Acting'), ('C', 'Confirmed')], default='Temporal', max_length=10),
        ),
    ]
