# Generated by Django 3.2.4 on 2021-08-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_auto_20210810_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassign',
            name='duration',
            field=models.SmallIntegerField(default=0),
        ),
    ]
