# Generated by Django 3.2.4 on 2021-08-31 06:06

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_alter_reassign_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=9),
        ),
        migrations.AddField(
            model_name='payroll',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
