# Generated by Django 3.2.4 on 2021-09-08 00:46

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20210905_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('value_type', models.CharField(default='Cr', max_length=2)),
                ('description', models.CharField(max_length=50)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
