# Generated by Django 4.0a1 on 2021-10-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_alter_employee_balance_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebalance',
            name='title',
            field=models.CharField(default='0821-Sales', max_length=30),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2021-10', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2021-10', max_length=7),
        ),
    ]
