# Generated by Django 4.0a1 on 2021-10-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_employeebalance_title_alter_creditnote_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2021-10', max_length=7),
        ),
    ]
