# Generated by Django 4.0a1 on 2021-11-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0028_employeebalance_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2021-11', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2021-11', max_length=7),
        ),
        migrations.AlterField(
            model_name='employee',
            name='banker',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2021-11', max_length=7),
        ),
        migrations.AlterField(
            model_name='reassign',
            name='to_branch',
            field=models.CharField(blank=True, choices=[('Badagry', 'Badagry'), ('Candy', 'Candy'), ('FG', 'FG'), ('Genesis', 'Genesis'), ('HQ', 'HQ'), ('Island', 'Island'), ('Stardom', 'Stardom'), ('Vino', 'Vino')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reassign',
            name='to_position',
            field=models.CharField(blank=True, choices=[('Accountant', 'Accountant'), ('Accounts-Clerk', 'Accounts-Clerk'), ('Analyst', 'Analyst'), ('Cashier', 'Cashier'), ('Driver', 'Driver'), ('GSM', 'GSM'), ('HRM', 'HRM'), ('MD', 'MD'), ('Marketing Manager', 'Marketing Manager'), ('SCM', 'SCM'), ('Sales Rep', 'Sales Rep'), ('Sales-Clerk', 'Sales-Clerk'), ('Stock-Keeper', 'Stock-Keeper'), ('Store-Keeper', 'Store-Keeper')], max_length=30, null=True),
        ),
    ]
