# Generated by Django 4.0a1 on 2021-11-13 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0029_alter_creditnote_period_alter_debitnote_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('resume_date', models.DateTimeField()),
                ('status', models.BooleanField(blank=True, default=None, null=True)),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
