# Generated by Django 4.0a1 on 2021-11-15 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_requestpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpermission',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='requestpermission',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
