# Generated by Django 4.0a1 on 2022-02-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_alter_creditnote_period_alter_debitnote_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'verbose_name_plural': 'Payroll'},
        ),
    ]
