# Generated by Django 4.0.2 on 2022-03-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_alter_payroll_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2022-03', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2022-03', max_length=7),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2022-03', max_length=7),
        ),
    ]
