# Generated by Django 4.0.3 on 2022-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0035_alter_creditnote_period_alter_debitnote_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2022-04', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2022-04', max_length=7),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2022-04', max_length=7),
        ),
        migrations.AlterField(
            model_name='reassign',
            name='to_branch',
            field=models.CharField(blank=True, choices=[('Badagry', 'Badagry'), ('FG', 'FG'), ('Genesis', 'Genesis'), ('Lagos Island', 'Lagos Island'), ('Stardom', 'Stardom'), ('Vino', 'Vino')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reassign',
            name='to_position',
            field=models.CharField(blank=True, choices=[('Accountant', 'Accountant'), ('Accounts Clerk', 'Accounts Clerk'), ('GSM', 'GSM'), ('MD', 'MD'), ('SCM', 'SCM'), ('Sales Clerk', 'Sales Clerk'), ('Stock-Keeper', 'Stock-Keeper'), ('Store-Keeper', 'Store-Keeper')], max_length=30, null=True),
        ),
    ]
