# Generated by Django 4.0.3 on 2022-04-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0036_alter_creditnote_period_alter_debitnote_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassign',
            name='to_branch',
            field=models.CharField(blank=True, choices=[('Front Gate', 'Front Gate'), ('Genesis', 'Genesis'), ('Lagos Island', 'Lagos Island'), ('Vino', 'Vino')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reassign',
            name='to_position',
            field=models.CharField(blank=True, choices=[('GSM', 'GSM'), ('HR', 'HR'), ('MD', 'MD'), ('SCM', 'SCM')], max_length=30, null=True),
        ),
    ]
