# Generated by Django 4.0.3 on 2022-04-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0038_alter_reassign_to_branch_alter_reassign_to_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reassign',
            name='to_branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reassign',
            name='to_position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
