# Generated by Django 4.0.3 on 2022-11-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0044_alter_creditnote_period_alter_debitnote_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2022-11', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2022-11', max_length=7),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2022-11', max_length=7),
        ),
    ]
