# Generated by Django 4.0.3 on 2023-01-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0047_alter_creditnote_period_alter_debitnote_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permit',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permit',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
