# Generated by Django 4.0.3 on 2023-03-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0048_permit_review_permit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2023-03', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2023-03', max_length=7),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2023-03', max_length=7),
        ),
    ]
