# Generated by Django 4.0.3 on 2023-04-20 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0049_alter_creditnote_period_alter_debitnote_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2023-04', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2023-04', max_length=7),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2023-04', max_length=7),
        ),
    ]
