# Generated by Django 4.2.1 on 2023-06-05 23:25

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0050_alter_creditnote_period_alter_debitnote_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminate',
            name='status',
            field=models.BooleanField(choices=[(True, 'On'), (False, 'Off')], default=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2023-06', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2023-06', max_length=7),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2023-06', max_length=7),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='salarychange',
            name='previous_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='salarychange',
            name='value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='suspend',
            name='penalty_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
