# Generated by Django 4.2.1 on 2023-06-09 23:23

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0051_terminate_status_alter_creditnote_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tax_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(5000)]),
        ),
        migrations.CreateModel(
            name='ReEngage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('approved_salary_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('approved_salary', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('terminated_date', models.DateField()),
                ('last_salary_paid_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('last_salary_paid', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
