# Generated by Django 4.2.14 on 2024-07-22 11:11

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0052_alter_employee_tax_amount_reengage'),
    ]

    operations = [
        migrations.AddField(
            model_name='welfare',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2024-07', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2024-07', max_length=7),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2024-07', max_length=7),
        ),
        migrations.AlterField(
            model_name='welfare',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10),
        ),
    ]
