# Generated by Django 5.1.2 on 2025-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0053_welfare_amount_currency_alter_creditnote_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2025-01', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2025-01', max_length=7),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2025-01', max_length=7),
        ),
    ]
