# Generated by Django 6.0.2 on 2026-06-04 14:40

import djmoney.models.fields
import djmoney.models.validators
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0054_alter_creditnote_period_alter_debitnote_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='period',
            field=models.CharField(default='2026-06', max_length=7),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='period',
            field=models.CharField(default='2026-06', max_length=7),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tax_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'NGN'), max_digits=10, validators=[djmoney.models.validators.MinMoneyValidator(0), djmoney.models.validators.MaxMoneyValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period',
            field=models.CharField(default='2026-06', max_length=7),
        ),
    ]
