# Generated by Django 6.0.2 on 2026-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0055_increase_tax_amount_max_digits'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('staff', 'period'), name='unique_payroll_staff_period'),
        ),
    ]
