# Generated by Django 6.0.2 on 2026-07-20 19:35

import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0056_payroll_unique_staff_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=4, unique=True)),
                ('threshold_amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('threshold_amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14)),
                ('methodology_note', models.TextField()),
                ('approved_date', models.DateField()),
                ('disclosed_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquityParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_code', models.CharField(max_length=20)),
                ('initial_capital_allocation_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('initial_capital_allocation', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('grant_date', models.DateField(help_text="Starts this participant's single maturity clock. Admin-set, never defaulted.")),
                ('status', models.CharField(choices=[('active', 'Active'), ('separated', 'Separated'), ('forfeited_cause', 'Forfeited (Cause)')], default='active', max_length=20)),
                ('fully_matured', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equity_participant', to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EquityClockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('grant', 'Grant'), ('profit_pool_credit', 'Profit Pool Credit'), ('vest_33', 'Vested 33%'), ('vest_66', 'Vested 66%'), ('vest_100', 'Vested 100%'), ('clawback', 'Clawback'), ('forfeiture_cause', 'Forfeiture (Cause)'), ('forfeiture_separation', 'Forfeiture (Separation)'), ('payout', 'Payout')], max_length=25)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_events', to='staff.equityparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='EquityStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=4)),
                ('file', models.FileField(upload_to='equity_statements/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='staff.equityparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='EquityShareAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=4)),
                ('pool_share_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_allocations', to='staff.equityparticipant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('participant', 'fiscal_year'), name='unique_equity_share_participant_fy')],
            },
        ),
    ]
