# Generated by Django 3.2.4 on 2021-08-20 12:49

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('store_type', models.CharField(choices=[('Lock-up', 'Lock-up'), ('Suit', 'Suit'), ('Warehouse', 'Warehouse')], max_length=30)),
                ('usage', models.CharField(choices=[('Storage', 'Storage'), ('Sell-out', 'Sell-out')], max_length=30)),
                ('owner', models.CharField(default='self', max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=11)),
                ('rent_amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('rent_amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=8)),
                ('capacity', models.IntegerField(help_text='33cl Can cases store can take')),
                ('expiry_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
