# Generated by Django 3.2.4 on 2021-08-21 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='Address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='stores',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2022, 8, 21)),
        ),
        migrations.AlterField(
            model_name='stores',
            name='owner',
            field=models.CharField(default='Self', max_length=50),
        ),
    ]
