# Generated by Django 3.2.4 on 2021-08-22 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210821_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stores',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stores',
            name='rent_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stores',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_type',
            field=models.CharField(choices=[('Lock-up', 'Lock-up'), ('Suite', 'Suite'), ('Warehouse', 'Warehouse')], max_length=30),
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount_paid_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('amount_paid', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=10)),
                ('expiry_date', models.DateField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.stores')),
            ],
        ),
    ]
