# Generated by Django 3.2.4 on 2021-08-31 06:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20210822_1322'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='stores',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='stores',
            name='store_type',
            field=models.CharField(choices=[('Lock-up', 'Lock-up'), ('Suite', 'Suite'), ('Warehouse', 'Warehouse'), ('Quarters', 'Quarters')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stores',
            name='usage',
            field=models.CharField(choices=[('Storage', 'Storage'), ('Sell-out', 'Sell-out'), ('Office', 'Office'), ('Apartment', 'Apartment')], max_length=30),
        ),
    ]
