# Generated by Django 3.2.4 on 2021-09-16 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20210831_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=10)),
                ('bank', models.CharField(choices=[('Access', 'Access'), ('Ecobank', 'Ecobank'), ('FCMB', 'FCMB'), ('Fidelity', 'Fidelity'), ('First Bank', 'First Bank'), ('GTB', 'GTB'), ('Heritage', 'Heritage'), ('Polaris', 'Polaris'), ('Stanbic', 'Stanbic'), ('Sterling', 'Sterling'), ('UBA', 'UBA'), ('Union Bank', 'Union Bank'), ('Unity', 'Unity'), ('Wema', 'Wema'), ('Zenith', 'Zenith')], max_length=10)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='warehouse.stores')),
            ],
        ),
    ]
