# Generated by Django 4.0a1 on 2022-02-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewal',
            name='expiry_date',
        ),
    ]
