# Generated by Django 4.0a1 on 2022-02-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_renewal_expiry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renewal',
            options={'verbose_name_plural': 'Renewal'},
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={'verbose_name_plural': 'Stores'},
        ),
    ]
