# Generated by Django 4.0.3 on 2022-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_renewal_options_alter_stores_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('Access', 'Access'), ('Wema', 'Wema'), ('UBA', 'UBA'), ('Union', 'Union'), ('Sterling', 'Sterling'), ('First Bank', 'First Bank'), ('GTB', 'GTB'), ('FCMB', 'FCMB'), ('Heritage', 'Heritage'), ('Diamond', 'Diamond')], max_length=30),
        ),
    ]
