# Generated by Django 4.0.3 on 2022-04-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('UBA', 'UBA'), ('Access', 'Access'), ('First Bank', 'First Bank'), ('GTB', 'GTB'), ('FCMB', 'FCMB'), ('Stanbic', 'Stanbic'), ('Wema', 'Wema'), ('Sterling', 'Sterling'), ('Polaris', 'Polaris'), ('Union', 'Union'), ('Diamond', 'Diamond'), ('Fidelity', 'Fidelity'), ('Unity', 'Unity'), ('Heritage', 'Heritage')], max_length=30),
        ),
    ]
