# Generated by Django 4.0.3 on 2022-04-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('UBA', 'UBA')], max_length=30),
        ),
    ]
