# Generated by Django 4.0.3 on 2022-04-08 05:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bankaccount',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
