# Generated by Django 4.0.3 on 2022-04-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0014_alter_bankaccount_managers_bankaccount_disabled'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bankaccount',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='stores',
            managers=[
            ],
        ),
    ]
