# Generated by Django 4.0.3 on 2022-05-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0015_alter_bankaccount_managers_alter_stores_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='capacity',
            field=models.IntegerField(help_text='How many 33cl Cans?'),
        ),
    ]
