# Generated by Django 4.2.14 on 2024-07-15 15:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_alter_stores_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stores',
            name='allocated_levy_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='stores',
            name='allocated_levy_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.CreateModel(
            name='StoreLevy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('amount_paid', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=7)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('party', models.CharField(max_length=30, verbose_name='Payable To')),
                ('payment_in_full', models.BooleanField(default=True, verbose_name='Full or Part Payment')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarks')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.stores')),
            ],
        ),
    ]
