# Generated by Django 4.2.14 on 2024-07-18 10:40

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_stores_allocated_levy_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='allocated_levy_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
