# Generated by Django 4.2.14 on 2024-07-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_alter_stores_allocated_levy_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='month',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='renewal',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
