# Generated by Django 4.2.14 on 2024-07-22 09:42

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_renewal_month_renewal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelevy',
            name='amount_paid',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12),
        ),
    ]
