# Generated by Django 3.2.4 on 2021-09-18 15:53

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=20)),
                ('year', models.PositiveSmallIntegerField(default=2021)),
                ('sales_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('sales', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('purchase_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('purchase', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('expenses_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('expenses', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('opening_value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('opening_value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('closing_value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('closing_value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
