# Generated by Django 3.2.4 on 2021-09-22 17:28

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20210918_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trademonthly',
            old_name='expenses_currency',
            new_name='direct_expenses_currency',
        ),
        migrations.RemoveField(
            model_name='trademonthly',
            name='expenses',
        ),
        migrations.AddField(
            model_name='trademonthly',
            name='direct_expenses',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trademonthly',
            name='direct_income',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trademonthly',
            name='direct_income_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='trademonthly',
            name='indirect_expenses',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trademonthly',
            name='indirect_expenses_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='trademonthly',
            name='indirect_income',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='trademonthly',
            name='indirect_income_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='gross_profit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022')], default=2021),
        ),
    ]
