# Generated by Django 3.2.4 on 2021-09-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20210922_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trademonthly',
            old_name='period',
            new_name='month',
        ),
    ]
