# Generated by Django 3.2.4 on 2021-09-26 04:42

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_rename_period_trademonthly_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('sales_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('sales', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('purchase_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('purchase', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('direct_expenses_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('direct_expenses', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('indirect_expenses_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('indirect_expenses', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('opening_value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('opening_value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('closing_value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('closing_value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('gross_profit_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('gross_profit', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('direct_income_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('direct_income', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('indirect_income_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('indirect_income', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='direct_expenses',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='indirect_expenses',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12),
        ),
    ]
