# Generated by Django 4.0a1 on 2022-02-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20210926_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademonthly',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2021, '2021'), (2022, '2022'), (2023, '2023')], default=2022),
        ),
    ]
