# Generated by Django 4.0a1 on 2022-02-23 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_alter_trademonthly_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradedaily',
            options={'verbose_name_plural': 'Daily'},
        ),
        migrations.AlterModelOptions(
            name='trademonthly',
            options={'verbose_name_plural': 'Monthly'},
        ),
    ]
