# Generated by Django 4.0.3 on 2022-09-25 10:35

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_alter_tradedaily_options_alter_trademonthly_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('profit_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('profit', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('adjusted_profit_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('adjusted_profit', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('capital_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('capital', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('liability_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('liability', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('loan_liability_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('loan_liability', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('fixed_asset_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('fixed_asset', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('current_asset_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('current_asset', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('investment_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('investment', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('suspense_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('suspense', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('difference_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('difference', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
