# Generated by Django 4.0.3 on 2022-09-26 07:42

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_balancesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='sundry_debtor',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='sundry_debtor_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3),
        ),
    ]
