# Generated by Django 4.0.3 on 2023-01-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_balancesheet_sundry_debtor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademonthly',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024')], default=2023),
        ),
    ]
