# Generated by Django 4.0.3 on 2023-03-23 07:54

import datetime
from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_alter_trademonthly_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('account_number', models.CharField(max_length=12)),
                ('bank', models.CharField(max_length=30)),
                ('bank_balance_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('bank_balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('lien_amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('lien_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('account_package_balance_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('account_package_balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('account_group', models.CharField(default='Business', max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
