# Generated by Django 4.0.3 on 2023-03-23 08:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_package_balance',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_package_balance_currency',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_balance',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_balance_currency',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='date',
        ),
        migrations.CreateModel(
            name='BankBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('bank_balance_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('bank_balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('account_package_balance_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('account_package_balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.bankaccount')),
            ],
        ),
    ]
