# Generated by Django 4.0.3 on 2023-04-20 00:09

import datetime
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_remove_bankaccount_account_package_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='XYZ', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('ledger', models.CharField(choices=[('CR', 'Cr'), ('DR', 'Dr')], default='CR', max_length=2)),
                ('account_type', models.CharField(choices=[('Ext', 'External'), ('Int', 'Internal')], default='Ext', max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bankbalance',
            unique_together={('bank', 'date')},
        ),
    ]
