# Generated by Django 4.2.1 on 2023-06-05 23:25

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_creditor_alter_bankbalance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='adjusted_profit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='capital_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='current_asset_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='difference_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='fixed_asset_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='investment_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='liability_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='loan_liability_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='profit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='sundry_debtor_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='suspense_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='lien_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='bankbalance',
            name='account_package_balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='bankbalance',
            name='bank_balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tradedaily',
            name='closing_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tradedaily',
            name='direct_expenses_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tradedaily',
            name='direct_income_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tradedaily',
            name='gross_profit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tradedaily',
            name='indirect_expenses_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tradedaily',
            name='indirect_income_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tradedaily',
            name='opening_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tradedaily',
            name='purchase_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='tradedaily',
            name='sales_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='closing_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='direct_expenses_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='direct_income_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='gross_profit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='indirect_expenses_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='indirect_income_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='opening_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='purchase_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='trademonthly',
            name='sales_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='creditor',
            unique_together={('account', 'date')},
        ),
    ]
