# Generated by Django 5.1.2 on 2025-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_alter_balancesheet_adjusted_profit_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademonthly',
            name='year',
            field=models.PositiveSmallIntegerField(choices=[(2024, '2024'), (2025, '2025'), (2026, '2026')], default=2025),
        ),
    ]
