# Generated by Django 6.0.2 on 2026-06-03 00:25

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0018_adjustment_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('expected_date', models.DateField()),
                ('flow_type', models.CharField(choices=[('IN', 'Inflow'), ('OUT', 'Outflow')], default='OUT', max_length=3)),
                ('category', models.CharField(choices=[('salary', 'Salary / Payroll'), ('rent', 'Rent'), ('loan', 'Loan Repayment'), ('tax', 'Tax'), ('supplier', 'Supplier Payment'), ('utility', 'Utility'), ('other', 'Other')], default='other', max_length=20)),
                ('is_recurring', models.BooleanField(default=False, help_text='Tick if this repeats monthly')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['expected_date'],
            },
        ),
    ]
