# Generated by Django 6.0.2 on 2026-06-03 00:43

import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0019_cash_projection'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.PositiveSmallIntegerField(default=2026)),
                ('budgeted_sales_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('budgeted_sales', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('budgeted_purchase_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('budgeted_purchase', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('budgeted_direct_expenses_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('budgeted_direct_expenses', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('budgeted_indirect_expenses_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('budgeted_indirect_expenses', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('budgeted_gross_profit_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('budgeted_gross_profit', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'NGN'), max_digits=12)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['year', 'month'],
                'unique_together': {('month', 'year')},
            },
        ),
    ]
