# Generated by Django 4.2.14 on 2024-07-25 00:27

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
