# Generated by Django 4.2.14 on 2024-07-25 18:42

from django.db import migrations, models
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_transaction_bankaccount_current_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disburse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(max_length=30)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=8)),
                ('purpose', models.CharField(max_length=200)),
                ('has_detail', models.BooleanField()),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
