# Generated by Django 4.2.14 on 2024-07-26 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0004_disburse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disburse',
            name='has_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=30)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('approved_by', models.CharField(blank=True, max_length=30, null=True)),
                ('particulars', models.CharField(blank=True, max_length=20, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
