# Generated by Django 4.2.14 on 2024-07-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_alter_disburse_has_detail_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashflow.bankaccount'),
            preserve_default=False,
        ),
    ]
