# Generated by Django 4.2.14 on 2024-07-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0006_withdrawal_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashflow.bankaccount'),
        ),
    ]
