# Generated by Django 4.2.14 on 2024-07-26 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0007_alter_withdrawal_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='stage',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InterbankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receiver_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfer', to='cashflow.bankaccount')),
                ('sender_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfer', to='cashflow.bankaccount')),
            ],
        ),
    ]
