# Generated by Django 4.2.14 on 2024-07-27 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0008_withdrawal_stage_interbanktransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='decided_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interbanktransfer',
            name='transfer_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
