# Generated by Django 4.2.14 on 2024-07-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashflow', '0009_remove_withdrawal_approved_by_withdrawal_decided_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to=settings.AUTH_USER_MODEL),
        ),
    ]
