# Generated by Django 4.2.14 on 2024-07-29 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0011_banktransfer_bankcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='opening_balance_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankcharges',
            name='post_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='post_date',
            field=models.DateField(),
        ),
    ]
