# Generated by Django 5.1.2 on 2025-01-22 16:14

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0014_cashcenter_cashtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3),
        ),
    ]
