# Generated by Django 4.0a1 on 2021-11-06 08:47

from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0029_alter_creditnote_period_alter_debitnote_period_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('value_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'Nigerian Naira')], default='NGN', editable=False, max_length=3)),
                ('value', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=10)),
                ('quantity_in', models.IntegerField(default=0)),
                ('in_date', models.DateField()),
                ('pack_type', models.CharField(choices=[('Pieces', 'Pieces'), ('Pack', 'Pack')], default='Pieces', max_length=10)),
                ('quantity_per_pack', models.IntegerField(default=0, help_text='zero means units are in pieces')),
                ('source', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='article_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_out', models.IntegerField()),
                ('out_date', models.DateField()),
                ('pack_type', models.CharField(choices=[('Pieces', 'Pieces'), ('Pack', 'Pack')], default='Pieces', max_length=10)),
                ('quantity_per_pack', models.IntegerField(default=0, help_text='zero means units are in pieces')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.article')),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
