# Generated by Django 4.0a1 on 2021-11-07 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='quantity_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='in_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='issuance',
            name='out_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
