# Generated by Django 4.0a1 on 2021-11-07 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('staff', '0029_alter_creditnote_period_alter_debitnote_period_and_more'),
        ('material', '0002_article_quantity_balance_alter_article_in_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_date', models.DateField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
        migrations.CreateModel(
            name='RequestArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='pack_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='quantity_per_pack',
        ),
        migrations.DeleteModel(
            name='Issuance',
        ),
        migrations.AddField(
            model_name='requestarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.article'),
        ),
        migrations.AddField(
            model_name='requestarticle',
            name='request_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='issuearticle',
            name='issued_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.requestarticle'),
        ),
    ]
