# Generated by Django 4.0a1 on 2021-11-07 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('material', '0003_issuearticle_requestarticle_remove_article_pack_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuearticle',
            name='issued_to',
        ),
        migrations.AddField(
            model_name='issuearticle',
            name='the_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='material.requestarticle', verbose_name='Article Requested'),
        ),
        migrations.AlterField(
            model_name='issuearticle',
            name='approved_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='requestarticle',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
