# Generated by Django 4.0a1 on 2021-11-08 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_remove_issuearticle_issued_to_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='requestarticle',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='issuearticle',
            name='the_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.requestarticle', verbose_name='Article Requested'),
        ),
    ]
