# Generated by Django 4.0a1 on 2021-11-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('material', '0005_alter_article_managers_alter_requestarticle_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuearticle',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='requestarticle',
            name='status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
