# Generated by Django 4.0a1 on 2022-02-23 06:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0034_alter_payroll_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('number_kids', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
