# Generated by Django 4.0a1 on 2022-02-24 09:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_alter_payroll_options'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('number_kids', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
